INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('1Rock In Rio', 'Shows de rock e atualidades', 'Rio de Janeiro', 'rodrigo_abdalla@outlook.com');
INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('2Libertadores', 'Campeonato Sul-americano', 'Morumbi', 'rodrigo_abdalla@outlook.com');
INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('3Rock In Rio', 'Shows de rock e atualidades', 'Rio de Janeiro', 'rodrigo_abdalla@outlook.com');
INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('4Libertadores', 'Campeonato Sul-americano', 'Morumbi', 'rodrigo_abdalla@outlook.com');
INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('5Rock In Rio', 'Shows de rock e atualidades', 'Rio de Janeiro', 'rodrigo_abdalla@outlook.com');
INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('6Libertadores', 'Campeonato Sul-americano', 'Morumbi', 'rodrigo_abdalla@outlook.com');
INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('7Rock In Rio', 'Shows de rock e atualidades', 'Rio de Janeiro', 'rodrigo_abdalla@outlook.com');
INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('8Libertadores', 'Campeonato Sul-americano', 'Morumbi', 'rodrigo_abdalla@outlook.com');
INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('9Rock In Rio', 'Shows de rock e atualidades', 'Rio de Janeiro', 'rodrigo_abdalla@outlook.com');
INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('10Libertadores', 'Campeonato Sul-americano', 'Morumbi', 'rodrigo_abdalla@outlook.com');
INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('11Rock In Rio', 'Shows de rock e atualidades', 'Rio de Janeiro', 'rodrigo_abdalla@outlook.com');
INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('12Libertadores', 'Campeonato Sul-americano', 'Morumbi', 'rodrigo_abdalla@outlook.com');
INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('13Rock In Rio', 'Shows de rock e atualidades', 'Rio de Janeiro', 'rodrigo_abdalla@outlook.com');
INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('14Libertadores', 'Campeonato Sul-americano', 'Morumbi', 'rodrigo_abdalla@outlook.com');
INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('15Rock In Rio', 'Shows de rock e atualidades', 'Rio de Janeiro', 'rodrigo_abdalla@outlook.com');
INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('16Libertadores', 'Campeonato Sul-americano', 'Morumbi', 'rodrigo_abdalla@outlook.com');
INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('17Rock In Rio', 'Shows de rock e atualidades', 'Rio de Janeiro', 'rodrigo_abdalla@outlook.com');
INSERT INTO TBL_EVENT (name, description, PLACE, EMAIL_CONTACT) VALUES ('18Libertadores', 'Campeonato Sul-americano', 'Morumbi', 'rodrigo_abdalla@outlook.com');
